version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: jwt_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

